{% set name = "min-dalle" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/min-dalle-{{ version }}.tar.gz
  sha256: a9043630fc9d4297cf63f0fc2f62096c16fb9a75d8bbf5d04b03452f9a9cb2da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.21
    - pillow >=7.1
    - python >=3.6
    - requests >=2.23
    - pytorch >=1.11
    - typing_extensions >=4.1

test:
  imports:
    - min_dalle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kuprel/min-dalle
  summary: A fast, minimal port of DALL E Mini with mega weights.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
